/* USER REDUCER TYPES */
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

/* UI REDUCER TYPES */
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_DASHBOARD = "SET_DASHBOARD";

/* DATA REDUCER TYPES */
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_USERS = "SET_USERS";
export const LOADING_DATA = "LOADING_DATA";
export const SET_BOOKS = "SET_BOOKS";
export const SET_BOOK = "SET_BOOK";
export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIE = "SET_MOVIE";
export const SET_USER_BOOKS = "SET_USER_BOOKS";
export const SET_USER_MOVIES = "SET_USER_MOVIES";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_BOOK_RESERVATIONS = "SET_BOOK_RESERVATIONS";
export const SET_BOOK_RSERVATION = "SET_BOOK_RSERVATION";
export const SET_SCRAPED_BOOKS = "SET_SCRAPED_BOOKS";

/* CART REDUCER TYPES */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";